services:
  jump-metrics:
    build: .
    # ECR image URL redacted
    # image: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/REPOSITORY:latest
    container_name: jump-metrics
    restart: unless-stopped
    ports:
      - "80:8080" 
    volumes:
      - ./storage:/app/storage
    environment:
      - NODE_ENV=production
      - PORT=8080

